### ISSUE TITLE
Napa `execute` promise only completes on request cancellation

### ISSUE THREAD

**Issue by dmitrif** [Microsoft/napajs#170]
Hello!

Currently testing out NapaJS in concurrency with Express. The idea is to offload JSON serialization / deserialization to a separate thread, the code is as follows:

```
const express = require('express');
const bodyParser = require('body-parser');
const http = require('http');
const napa = require('napajs');

const jsonZone = napa.zone.create('data-io', { workers: 4 });

const app = express();

const parseJson = data => {
  return JSON.parse(data);
}

const handleRequest = (req, res, next) => {
  console.log('handling request');
  jsonZone.execute(parseJson, [req.body], ).then((result) => {
    res.json({ok: 'ok'});
  }).catch(e => console.error(e));
};

app.use('/', bodyParser.text({ type: 'application/json' }), handleRequest);

const httpServer = http.createServer(app).listen(9999);

httpServer.on('listening', () => {
  const host = httpServer.address().address;
  const port = httpServer.address().port;

  console.log('Listening', { binding: { host, port }});
});
```

Whenever a request is made, the log is correct `handling request`. But the promise `then` is not executed until the request is timed out.

I am probably doing something very dumb... However, can't figure out what it is?

Happy holidays!

**Comment by dmitrif** [comment]
This is happening with Node 6.11.1 on Mac OS.

**Comment by daiyip** [comment]
Seem it's similar to issue #139, we have fixed this issue on version 0.1.7. Please check if this resolves your issue.

**Comment by dmitrif** [comment]
Hi, @daiyip ! I am currently testing with 0.1.7 and the problem persists. Thank you.

**Comment by fs-eire** [comment]
I've checked the javascript source in the napajs@0.1.7 from NPM. It looks like the fix (#141) is not included, due to something wrong in the publish process.

I've published [0.1.8](https://github.com/Microsoft/napajs/releases/tag/0.1.8) and verified the fix is included.

Also, a test case should be added to cover the callback from Napa to Node.
